# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'SwiftFlickrApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftFlickrApp
  pod 'AFNetworking'
  pod 'SVProgressHUD'

  target 'SwiftFlickrAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
